### ISSUE TITLE
Add refresh rate

### ISSUE THREAD

**Issue by KatamariJr** [foxx1337/foo_nowplaying2#3]
Hello! Thanks for making this. The old version of foo_np_simple had a way to refresh the output every X seconds. I used this to show a progress bar for the song as it updated. Can you add the feature to enable refreshing every X seconds?

This is what my format string looked like, youll see it makes a progress bar. 
```
[%genre%] 
$crlf()
%title% 
$crlf() $crlf()
[%playback_time%] [$progress(%_time_elapsed_seconds%, %_time_total_seconds%, 30,'█','─')] [%length%]
```

**Comment by foxx1337** [comment]
Ha, this makes sense!

**Comment by KatamariJr** [comment]
Any plans to implement this soon?

**Comment by bmthorn** [comment]
![Untitled](https://github.com/foxx1337/foo_nowplaying2/assets/126990085/8f3bbdb7-4036-4c32-a5ec-af2acc00112b)
I'm also in need of this feature! The event options were also part of this component.

**Comment by foxx1337** [comment]
Maybe it's a bit cluttered now, but I like to see all the options at once, and not have them disappear on action:
![image](https://github.com/foxx1337/foo_nowplaying2/assets/2565912/47893070-d5e0-402f-a1eb-893a14b8d563)

Added these options just for the Now Playing tab, as they can't be too useful in the others, will rethink should the need arise.
