### ISSUE TITLE
%datetime% still a no-go in 4.2

### ISSUE THREAD

**Issue by sveakul** [foxx1337/foo_nowplaying2#6]
1.  
![np2](https://github.com/foxx1337/foo_nowplaying2/assets/130251824/2ef9bede-d989-494c-a7ce-e07df4606cc3)

2. 
![datetime](https://github.com/foxx1337/foo_nowplaying2/assets/130251824/b11fdaf7-ba9c-46c6-bb4f-540b4a78c440)

3. 
? : Alternative - Indie Pop Rocks! [SomaFM]
? : Real Estate - Water Underground
? : Alternative - Radio Paradise (128k aac)
? : Mathias Duplessy - Tcheren Deya

Also, still no "last-played first" option.  Example above is from streaming radio logfile.

**Comment by foxx1337** [comment]
Oops, forgot a `nullptr` - https://github.com/foxx1337/foo_nowplaying2/blob/514dd66a00694c6712d925c5ca42b18136a97b7d/src/nowplaying.cpp#L245

Also reordering the log doesn't look that terrible.
