### ISSUE TITLE
Feature Request :: UDP/IP Output

### ISSUE THREAD

**Issue by gogonowski** [foxx1337/foo_nowplaying2#7]
Any chance of adding UDP/IP Output?
Specify IP Address and Port.
It can follow the same parameters as the Text File.
Thanks for the consideration.

**Comment by foxx1337** [comment]
I'm thinking of adding "run command" functionality. A script can be used, and that script can be associated with a web server that does what you describe here.

The idea is to not spread this functionality too thin, keep it minimal within foobar.

**Comment by gogonowski** [comment]
Looking for the ability to send Now Playing info to a UDP/IP Port, such as a streaming audio encoder or possibly digital signage.

It can use the same template approach as the Text File, except it would be realtime data, and not a file.

Let me know if you need a packet capture as an example.

Thanks.

**Comment by foxx1337** [comment]
This should be achievable with the "Run" tab from 5.0.
