### ISSUE TITLE
Now playing output cleared on "Stop" event

### ISSUE THREAD

**Issue by resistiv** [foxx1337/foo_nowplaying2#9]
Howdy!

I'm currently attempting to use this plugin for streaming output for OBS to display what music is currently playing.
I am using the following format string, which I was previously using with foobar_np_simple:
`Now Playing: $if(%isplaying%,%artist% - %title%$if(%ispaused%, |PAUSED|),Nothing.)`

I am currently using the On New Track, On Pause, and On Stop events. So, the expected output is something like:
While playing: `Now Playing: Artist - Song`
While paused: `Now Playing: Artist - Song |PAUSED|`
While stopped: `Now Playing: Nothing.`

The playing and paused states seem to work fine, but when stopping a track it seemingly clears the output instead of evaluating the format string.
I've also tried without the third argument of the `if` clause, but the output is still cleared on stop.
I've attached a video demonstration of the issue: https://github.com/user-attachments/assets/019e6509-0514-4ca2-8f60-23286a8ed30d

Does it seem like this something that is occurring due to a configuration issue on my end? Or could this be a bug?
It seems like Hydrogen Audio user SushiKishi [ran into a similar issue](https://hydrogenaud.io/index.php/topic,124427.msg1034590.html#msg1034590), but they seemingly never followed up, so I'm not aware of a fix.

Thanks for making this project, it's nice to see folks reviving and maintaining some of these older plugins! :)

**Comment by foxx1337** [comment]
Definitely a bug, thanks for pointing it out!

**Comment by foxx1337** [comment]
Should be fixed in 5.0, let me know!

**Comment by resistiv** [comment]
Seems to be fixed, thanks so much!
